### ISSUE TITLE
Please invite me to your organization

### ISSUE THREAD

**Issue by nikkikharkwal** [openAOD/Join#100]
Hello
My name is Nikki Kharkwal.
Email-ID :- nikki.kharkwal@gmail.com
I would like to join the organization to learn and contribute together.

**Comment by ChlorinePentoxide** [comment]
Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
