### ISSUE TITLE
For joining openAOD organization

### ISSUE THREAD

**Issue by Ash-KODES** [openAOD/Join#102]
name: @Ash-KODES

I am very interested in this organization.
Thanks.

**Comment by ChlorinePentoxide** [comment]
Welcome to openAOD, sorry for the delay in replying! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
