### ISSUE TITLE
i want to be a member of your organization 

### ISSUE THREAD

**Issue by pratik-wadhai** [openAOD/Join#104]
https://github.com/pratik-wadhai
pratikwadhai001@gmail.com

**Comment by ChlorinePentoxide** [comment]
Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
