### ISSUE TITLE
Join this organization

### ISSUE THREAD

**Issue by supercomet329** [openAOD/Join#106]
Hi,
I am a full stack developer and I would like to contirbute to make this community rich.
Please send me an invite.
My github account is https://github.com/supercomet329

**Comment by ChlorinePentoxide** [comment]
Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
