### ISSUE TITLE
Want to join this Organization

### ISSUE THREAD

**Issue by geektalent1010** [openAOD/Join#109]
I am a full stack developer with 7+ years experience of all kinds of modern javascript frameworks.
I like sharing my knowledge and help other people and learn from them.
Thank you,

**Comment by ChlorinePentoxide** [comment]
Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
