### ISSUE TITLE
Add to the participants please

### ISSUE THREAD

**Issue by Sinrez** [openAOD/Join#110]
Hello.
I am interested in new technologies and language.
I am currently learning Python.
This project is interesting for my self-education

Thank you for the opportunity

Regards, Alex

**Comment by ChlorinePentoxide** [comment]
Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
