### ISSUE TITLE
Request to join.

### ISSUE THREAD

**Issue by phoenixdevguru** [openAOD/Join#113]
GitHub username: @phoenixdevguru
Discord username: @phoenixdevguru#7561

I want to be a member of openAOD!!!

**Comment by aryashah2k** [comment]
Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
