### ISSUE TITLE
I would like to join.

### ISSUE THREAD

**Issue by legendsort** [openAOD/Join#115]
I am full-stack developer. I would like to meet, discuss and get involved in challenges.

**Comment by aryashah2k** [comment]
Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
