### ISSUE TITLE
richforest0506

### ISSUE THREAD

**Issue by richforest0506** [openAOD/Join#118]
I want to contribute your open-source repository.
Please invite me.
mail: richforest0506@gmail.com
Github username: richforest0506
Thanks.

**Comment by aryashah2k** [comment]
Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
