### ISSUE TITLE
I want to join community

### ISSUE THREAD

**Issue by geeky-sambhav** [openAOD/Join#119]
username : geeky-sambhav
I have been following the openAOD community for some time now and have been impressed with the quality of work that has been produced by the members. I believe that my skills and experience would be a valuable asset to the community and I am eager to contribute to open-source projects and learn from other talented developers.

**Comment by aryashah2k** [comment]
Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
