### ISSUE TITLE
join request

### ISSUE THREAD

**Issue by Lil-Adonis** [openAOD/Join#120]
I have always been interested in technology and programming, and I'm eager to learn more about the latest trends and techniques in this rapidly evolving field. I'm also excited about the opportunity to work on projects that have a real-world impact, whether it's developing open-source software, building websites, or creating apps that solve important problems.

**Comment by ChlorinePentoxide** [comment]
Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
