### ISSUE TITLE
I'd like to join

### ISSUE THREAD

**Issue by iamsuiux** [openAOD/Join#122]
DoBestMan

**Comment by adopted-t-kunkel** [comment]
I want to join to your community!

**Comment by ChlorinePentoxide** [comment]
@DoBestMan Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
