### ISSUE TITLE
I want to contribute to this organization.

### ISSUE THREAD

**Issue by anhtran917** [openAOD/Join#123]

**Comment by anhtran917** [comment]
username: anhtran917
email: fullstackdeveloper917@gmail.com
I am interested in joining the OpenAOD team on GitHub because I share a passion for open-source projects and believe in the mission and goals of the team.

**Comment by ChlorinePentoxide** [comment]
@anhtran917 Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!

**Comment by anhtran917** [comment]
Thanks, I joined.
