### ISSUE TITLE
Join to organization

### ISSUE THREAD

**Issue by rubiin** [openAOD/Join#124]
Just want to connect to the organization

**Comment by adopted-t-kunkel** [comment]
I want to join to your community!

**Comment by ChlorinePentoxide** [comment]
@rubiin Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!

**Comment by ChlorinePentoxide** [comment]
@devlancer-lucas Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
