### ISSUE TITLE
Please send me invitation.

### ISSUE THREAD

**Issue by marc316** [openAOD/Join#126]
Hello. 

My name: Marc Vaccaro
My Github Username: Marc316

I really would love to jump into this community.

Thank you.

**Comment by ChlorinePentoxide** [comment]
@marc316 Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
