### ISSUE TITLE
Joining AOD community

### ISSUE THREAD

**Issue by The-Phoenics** [openAOD/Join#130]
Github username : Karansemwal

I want to join the community for learning opportunities, networking and collaborations, feedbacks & improvement, sharing knowledge and helping out peers.

**Comment by ChlorinePentoxide** [comment]
@Karansemwal Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
