### ISSUE TITLE
Can I join this Organization

### ISSUE THREAD

**Issue by Phoenix-Genius** [openAOD/Join#131]
Hello,
I am @charles0830.
I am senior full stack developer with 10+ years of development experience. 
I have used GitHub for 13 years but have no knowledge about organization.
So I am going to start with you.
Thanks,
chberry830@gmail.com

**Comment by aryashah2k** [comment]
@charles0830  Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
