### ISSUE TITLE
Join Community

### ISSUE THREAD

**Issue by ArthurDotSaito** [openAOD/Join#139]
Hello everyone, 
I'd like to join the community. I'd seen some of the repositories and appreciate if I could contribut. I have a good knowledge in C++, C, Javascript, C# and I'm currently working as a Software Architect.
My github is ArthurDotSaito.

**Comment by aryashah2k** [comment]
Hello @ArthurDotSaito , happy to have here at openAOD, I have sent an invite to join the org!
