### ISSUE TITLE
I hope to join this community

### ISSUE THREAD

**Issue by top-web-talent** [openAOD/Join#151]
As a senior full stack engineer, I met the openAOD Community through various online platforms like GitHub, Discord, and Twitter. What I really dig about this community is their focus on open-source collabs, innovation, and sharing knowledge. The peeps here are super skilled and passionate about tech, creating a rad and supportive vibe for learning and leveling up.

I'm keen to join the openAOD Community because I believe in the power of community-driven dev and the impact it can have on advancing tech. I'm excited to bring my skills to the table, soak up knowledge from other talented folks, and be part of a crew that values creativity, teamwork, and always leveling up in software dev.

**Comment by aryashah2k** [comment]
Hey @top-web-talent , welcome to OpenAOD, I have sent an invite to join this org, happy to have you here!

**Comment by top-web-talent** [comment]
how can I contact with you?

**Comment by top-web-talent** [comment]
discord name???
