### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by nagpalnitesh** [openAOD/Join#154]
Hi 👋🏻 

I'm excited about the opportunity to contribute to an open-source developer association dedicated to enhancing tools, libraries, and learning resources for fellow developers. With over 4 years of experience as a software engineer, I'm eager to collaborate with like-minded individuals and make meaningful contributions to the community. Joining this organization will allow me to grow professionally and give back to the developer community which has enriched my career journey.

My GitHub handle: nagpalnitesh
I am looking forward to the possibility of joining your team.

**Comment by aryashah2k** [comment]
Hello there, welcome to openAOD, I have sent an invite to join the org. Happy to have you here : )
