### ISSUE TITLE
Please invite me to this organization

### ISSUE THREAD

**Issue by lkim227** [openAOD/Join#172]
My github name is @lkim227 and my email is lucas98kim227@gmail.com ...
Getting web3 job is my next dream. I am so touched about this web3 community.
Need to learn more and contribute to build my web3 career.

**Comment by aryashah2k** [comment]
Hey @lkim227 , happy to have you be a part of openAOD! I ahve sent an invite to join us !

**Comment by lkim227** [comment]
> Hey @lkim227 , happy to have you be a part of openAOD! I ahve sent an invite to join us !

Hey @aryashah2k, thanks!  Is there any client or an ongoing project right now?
Do you have a full-time job?
I'd like to hear you.
