### ISSUE TITLE
Request to join organization

### ISSUE THREAD

**Issue by Nyae44** [openAOD/Join#176]
### GitHub Username
**[Nyae44](https://github.com/Nyae44)**

### Email
**tingadaley@gmail.com**

### Reason for Joining
I want to join the openAOD organization to contribute to its projects and collaborate with others. I'm a Python Django developer eager to learn and help improve the community.

Thank you!

**Comment by aryashah2k** [comment]
Hey @Nyae44 , super happy to have you here, welcome to openAOD! I have sent an invite to join the community

**Comment by Nyae44** [comment]
Hey @aryashah2k I am yet to receive the invitation email
