### ISSUE TITLE
Please can I join this org?

### ISSUE THREAD

**Issue by CodingSpecies** [openAOD/Join#46]
Please can I join this organisation?
I would like to learn and also help others in this org. Thank you.

**Comment by aryashah2k** [comment]
Sure, Have sent you an invite!

**Comment by CodingSpecies** [comment]
@aryashah2k for some reason the invite hasn't seemed to have sent. Thank you.

**Comment by aryashah2k** [comment]
Hi, apparently, the 7 day period to accept the invitation has been expired, that's why.
![image](https://user-images.githubusercontent.com/73865728/156922113-0403ac92-a32e-4141-88e0-c4c15174b4c9.png)
I'll send a new invite right away, make sure you accept it within 7 days!

**Comment by CodingSpecies** [comment]
Sorry for that. Thank you.
