### ISSUE TITLE
Join

### ISSUE THREAD

**Issue by HarmonySkull** [openAOD/Join#58]
Github Email ID: developer@harmonyskull.codes

Github Username: HarmonySkull

A FrontEnd Developer who really likes technology, new things and likes to join many organizations. Love open source.

JS, TS & Dart enthusiast, experience with React, NextJS, React Native & Flutter.

**Comment by ChlorinePentoxide** [comment]
@HarmonySkull Welcome to OpenAOD, I will be sending a invite very soon. If you have any query or want to start contributing to our organization please feel free to message me on our Discord server (https://discord.gg/RGPPrwSZ). Cheers
