### ISSUE TITLE
Join

### ISSUE THREAD

**Issue by ParadoxElder** [openAOD/Join#59]
Github Email ID: david@themadfox.com

Github Username: ParadoxElder

A FrontEnd Developer who really likes technology, new things and likes to join many organizations. Love open source.

JS, TS & Dart enthusiast, experience with React, NextJS, React Native & Flutter.

**Comment by aryashah2k** [comment]
Hey there @ParadoxElder , I've sent an invite to join the org. Feel free to turn the membership visibility on so that the org badge displays on your profile page under your organizations!

**Comment by ChlorinePentoxide** [comment]
@ParadoxElder Also, if you have any query or want to start contributing to our organization please feel free to message me on our Discord server (https://discord.gg/RGPPrwSZ). Cheers
