### ISSUE TITLE
Join

### ISSUE THREAD

**Issue by theashishgavade** [openAOD/Join#60]
Github Email ID: [ashugavade67@gmail.com](mailto:ashugavade67@gmail.com)

Github Username: theashishgavade

A FrontEnd Developer who really likes technology, new things and likes to join many organizations. Love open source.

JS, TS & Dart enthusiast, experience with React, NextJS, React Native & Flutter.

**Comment by aryashah2k** [comment]
Hey there @theashishgavade, welcome to the team. Feel free to make your membership public. @ChlorinePentoxide will share the discord server link too which you can join and be part of the community.

**Comment by ChlorinePentoxide** [comment]
@theashishgavade Also, if you have any query or want to start contributing to our organization please feel free to message me on our Discord server (https://discord.gg/RGPPrwSZ). Cheers
