### ISSUE TITLE
invite me

### ISSUE THREAD

**Issue by SoftwareArchitect9817** [openAOD/Join#61]
.invite me

**Comment by aryashah2k** [comment]
@SoftwareArchitect9817 , welcome to openAOD, I've sent an invite. Feel free to make your membership visibility public! 
You can meet the community members on Discord too: https://discord.gg/RGPPrwSZ

**Comment by ChlorinePentoxide** [comment]
@SoftwareArchitect9817 Also if you would like to contribute please message me directly on discord. Cheers
