### ISSUE TITLE
Join

### ISSUE THREAD

**Issue by TitanRGB** [openAOD/Join#63]
Github Email ID: duanshuxunhuan@outlook.com
Github Username: TitanRGB

`duanshuxunhuan@outlook.com` `TitanRGB`

A CE student, want to join for fun and study.

**Comment by aryashah2k** [comment]
Welcome to openAOD, @TitanRGB . An invite has been sent.

**Comment by ChlorinePentoxide** [comment]
@TitanRGB Here is our Discord invite: https://discord.gg/C4p6RCG2; Please feel free to message me if you would want to contribute to our project.
