### ISSUE TITLE
Join

### ISSUE THREAD

**Issue by imhunterand** [openAOD/Join#64]
Github Email ID: [imhunterand@cyberservices.com](mailto:imhunterand@cyberservices.com)
Github Username: imhunterand

A CE student, want to join for vulnerability analysis contribute at community repository and study.

**Comment by ChlorinePentoxide** [comment]
@imhunterand Here is our Discord invite: https://discord.gg/C4p6RCG2; Please feel free to message me if you would want to contribute to our project.
I will be sending an invite very soon.
Cheers. 
Chlorine Pentoxide

**Comment by ChlorinePentoxide** [comment]
Here is our Discord invite: https://discord.gg/C4p6RCG2; Please feel free
to message me if you would want to contribute to our project.
I will be sending an invite very soon.
Cheers.
Chlorine Pentoxide
