### ISSUE TITLE
Add collaborator to the organization

### ISSUE THREAD

**Issue by cixtor** [openAOD/Join#65]
> *Why do you want to join the organzition?*

I have been an active member of the open-source community on GitHub and other platforms, and it is always a joy to find like-minded people willing to share knowledge and experiences. I would love to join thir GitHub organization to help many more developers become excellent open-source maintainers.

**Comment by ChlorinePentoxide** [comment]
Hey @cixtor, Welcome to openAOD.
I have sent you an invitation for joining our organisation. Please do also join our Discord server (https://discord.gg/C4p6RCG2).
If you want to start contributing to our project or have any questions regarding the project, please feel free to message me.
Cheers.
