### ISSUE TITLE
Please add me to openAOD

### ISSUE THREAD

**Issue by VipinChaudhary31** [openAOD/Join#68]
Hello,
I want to be part your organization.
I am really interested in your organization and your work.
I am a student but i want to gain some real life experience before completing my education as it will give me a edge.
I want to learn new tech with your help.
Please add me to your organization
Thank you

**Comment by VipinChaudhary31** [comment]
Thank You for adding to your Org

**Comment by aryashah2k** [comment]
Hey there @VipinChaudhary31 , glad to have you as a member, I've sent the invite, feel free to make your membership public and also join our discord server: https://discord.gg/C4p6RCG2
