### ISSUE TITLE
Please invite me.

### ISSUE THREAD

**Issue by DevStar0202** [openAOD/Join#75]
Please invite me to your github group.
Here is Daivid Morgan from Macedonia.
I love teamwork and I really wanna be one of your teammates.

Thanks. Daivid

**Comment by DevStar0202** [comment]
Thanks.

**Comment by DevStar0202** [comment]
Name : "Daivid Morgan"
Github Name : "DevStar0202"
Discord Name : "DevStar0202"

I really wanna be one of your group and I will contribute your github repositories toegether,

Thanks. Daivid
@DevStar0202

**Comment by ChlorinePentoxide** [comment]
Hey David, Welcome to openAOD. I will be sending an invite to join the organization shortly. Feel free to join our Discord server: https://discord.gg/wZ83xSJSsN . If you have any questions regarding the project or about contributions do contact me. If you need to ask anything please fell free to do so here. After you can confirm that you have joined the organization I will go ahead and close the other 2 issues as well. Cheers. Have a great day,

**Comment by DevStar0202** [comment]
Thanks.

**Comment by ChlorinePentoxide** [comment]
Sure, anytime.
