### ISSUE TITLE
danilosantanadeveloper

### ISSUE THREAD

**Issue by danilosantanadeveloper** [openAOD/Join#79]
I'd love to contribute to building websites

**Comment by ChlorinePentoxide** [comment]
@danilosantanadeveloper Hey Welcome to openAOD! I will be sending an invite very soon. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN . If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
