### ISSUE TITLE
Want to join the organization

### ISSUE THREAD

**Issue by Kapoor-0905** [openAOD/Join#80]
Hello 
GitHub username: Kapoor-0905
GitHub mail id: 500097111@stu.upes.ac.in

I want to join this open source organization as my specialization in my graduation period is Open source and standards, also this will enhance my skills and will contribute much in your org.

**Comment by ChlorinePentoxide** [comment]
@Kapoor-0905 Hey Welcome to openAOD! I will be sending an invite very soon. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN . If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
