### ISSUE TITLE
I hope to join this group

### ISSUE THREAD

**Issue by Forest410** [openAOD/Join#82]

**Comment by ChlorinePentoxide** [comment]
@Forest410 Hey Welcome to openAOD! I will be sending an invite very soon. We also recommend joining our Discord server : [https://discord.gg/wZ83xSJSsN ](https://discord.gg/wZ83xSJSsN%C2%A0). If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
