### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by hiiruki** [openAOD/Join#83]
I want to contribute to open-source projects

**Comment by ChlorinePentoxide** [comment]
@hiiruki  Hey Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN . If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
