### ISSUE TITLE
Please invite me into your org.

### ISSUE THREAD

**Issue by rot0505** [openAOD/Join#84]
Hi, I'd like to join your organization.
Github id: rot0505
Github email: jamesdev0505@gmail.com
Thanks.

**Comment by ChlorinePentoxide** [comment]
Hey Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : [https://discord.gg/wZ83xSJSsN](https://discord.gg/wZ83xSJSsN). If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
