### ISSUE TITLE
Please invite me to your org

### ISSUE THREAD

**Issue by khushimarothi** [openAOD/Join#85]
mail id:khushimarothi2002@gmail.com
Want to connect with diverse group of people and contribute to open source

**Comment by ChlorinePentoxide** [comment]
Hey @khushimarothi!
Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
