### ISSUE TITLE
Looking forward to getting involved and contributing to the community 

### ISSUE THREAD

**Issue by samuel-ma** [openAOD/Join#87]
My username is @samuel-ma
I  found this community through one of my followers
Would love to join and contribute some project ideas

**Comment by ChlorinePentoxide** [comment]
Hey @samuel-ma!
Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
