### ISSUE TITLE
invitation required to join org

### ISSUE THREAD

**Issue by sulamanshahbukhari** [openAOD/Join#91]
hi I'm looking forward to be a part of this community to upskill my skill set and learn from fellow contributors thanks
my github https://github.com/sulamanshahbukhari

**Comment by ChlorinePentoxide** [comment]
Hey @sulamanshahbukhari !!
Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
