### ISSUE TITLE
Invitation to me this community

### ISSUE THREAD

**Issue by Dragon1207** [openAOD/Join#92]
Github Username: Dragon1207

Please invite me to this community. Thanks

**Comment by aryashah2k** [comment]
Hey @Dragon1207  !!
Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
