### ISSUE TITLE
Invite me to this organization.

### ISSUE THREAD

**Issue by hodler-smart** [openAOD/Join#94]
name: @alphadev102

I am very interested in this organization.
Let me join here.
Thanks.

**Comment by ChlorinePentoxide** [comment]
Hey @alphadev102 !!
Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
