### ISSUE TITLE
Invitation to organization

### ISSUE THREAD

**Issue by arjunan-k** [openAOD/Join#98]
I would like to be part of the Open Source Community.
@aryashah2k

**Comment by ChlorinePentoxide** [comment]
@arjunan-k 
Welcome to openAOD! I have sent an invite to join our organization. We also recommend joining our Discord server : https://discord.gg/wZ83xSJSsN. If you have any questions regarding contributing or anything else feel free to write here or ping me on Discord. Cheers. Have a great day ahead of you!
